### ISSUE TITLE
Error when clicking on a file in the list

### ISSUE THREAD

**Issue by berengerelagrange** [vdelachaux/4DPop-XLIFF-Pro#8]
Hello Vincent,

When I select a group or a string and I want to select another file, I have an error.
If I select first the same file already selected and then select another file, I don't have any error.

https://github.com/vdelachaux/4DPop-XLIFF-Pro/assets/112881843/39a0ace2-9aa1-42d7-b694-e7bf4cfd11b1

Thanks :)

**Comment by vdelachaux** [comment]
fixed with #7
